### ISSUE TITLE
Why does readme mention MySQL when this is a Postgres backup image?

### ISSUE THREAD

**Issue by flyte** [jmcarbo/docker-postgres-backup#7]
There are a couple of mentions of MySQL in the readme that don't seem to make sense.

- In the PG_HOST variable of the `docker run` command in the Usage section
- In the following quote:

> Moreover, if you link jmcarbo/docker-postgres-backup to a postgres container (e.g. tutum/mysql) 

Shouldn't this suggest a postgres image, and not a mysql one?

**Comment by jmcarbo** [comment]
updated
